# Generated by Django 5.2.4 on 2025-07-08 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=25)),
                ('barrio', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_general', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('descripcion_dano', models.TextField()),
                ('paga_revision', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('garantia', 'Garantía')], default='pendiente', max_length=20)),
                ('numero_ingreso', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.equipo')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('garantia', 'Garantía')], max_length=20)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ingreso')),
            ],
        ),
    ]
