# Generated by Django 5.2.4 on 2025-07-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_ingreso_es_garantia_imagenhistorial_imageningreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialequipo',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='es_reporte_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='recomendaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='repuestos_usados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
