# Generated by Django 5.2.4 on 2025-07-27 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_historialequipo_diagnostico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=6, unique=True)),
                ('ultimo_numero', models.IntegerField(default=0)),
            ],
        ),
    ]
