# Generated by Django 5.2.4 on 2025-07-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_contadoringreso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='barrio',
        ),
    ]
