# Generated by Django 5.2.4 on 2025-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_cliente_barrio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='recibido_por',
            field=models.CharField(choices=[('alavaro', 'Alvaro Caballero'), ('sebastian', 'Sebastián Berrio'), ('juan', 'Juan Carlos')], default='alvaro', max_length=30),
        ),
    ]
