# Generated by Django 5.2.4 on 2025-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_alter_ingreso_recibido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialequipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('revisado', 'Revisado'), ('reparacion', 'En reparación'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('revisado', 'Revisado'), ('reparacion', 'En reparación'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='recibido_por',
            field=models.CharField(choices=[('alvaro', 'Alvaro Caballero'), ('sebastian', 'Sebastián Berrio'), ('juan', 'Juan Carlos'), ('david', 'David Chavarria')], default='david', max_length=30),
        ),
    ]
