# Generated by Django 5.2.4 on 2025-11-14 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_historialequipo_estado_alter_ingreso_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialequipo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente por revisión'), ('reparacion', 'En reparación'), ('revisado', 'Revisado'), ('autorizado', 'Autorizado'), ('reparado', 'Reparado'), ('entregado', 'Entregado'), ('devolucion', 'Devolución'), ('garantia', 'Garantía')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='ImagenSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='seriales/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_serial', to='gestion.equipo')),
            ],
            options={
                'verbose_name': 'Imagen de serial',
                'verbose_name_plural': 'Imagenes de serial',
            },
        ),
    ]
