# Generated by Django 5.2.4 on 2025-08-12 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_historialequipo_realizado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialequipo',
            name='realizado_por',
        ),
    ]
