# Generated by Django 5.2.4 on 2025-11-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_historialequipo_estado_alter_ingreso_estado_and_more'),
        ('gestion', '0008_remove_historialequipo_realizado_por'),
    ]

    operations = [
    ]
