# Generated by Django 5.2.4 on 2026-06-26 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_historialequipo_estado_alter_ingreso_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
    ]
