# Generated by Django 5.2.4 on 2026-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_ingreso_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenhistorial',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='imageningreso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='imageningreso',
            name='orden',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imagenserial',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
