# Generated by Django 5.2.4 on 2026-06-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_ingreso_options_historialequipo_realizado_por'),
        ('gestion', '0014_finalizar_recibido_por'),
    ]

    operations = [
    ]
